<?php

use Drupal\Core\Template\Attribute;

/**
 * @file
 * Theme for Vue views.
 */
function template_preprocess_dayspan_vuetify(&$variables) {
  //$view = $variables['view'];
  //ksm($view);
  /*
  $options = $view->style_plugin->options;
  $display_format = $options['display_format'];
  //$rows = $variables['rows'];*/
  /* Add this view to drupal settings */
  //$variables['view_id'] = $viewid = $view->Id();
  /*$variables['#attached']['drupalSettings']['ds']['view'] = [
    'viewid' => $viewid
  ];*/
}
